# Generated by Django 4.1.7 on 2023-03-08 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_continent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=35)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cities.continent')),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_country', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cities.country')),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_city', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
